CREATE TABLE ISSUES (
  ID BIGINT NOT NULL ,
  GROUP_ID BIGINT NOT NULL ,
  TEXT VARCHAR,
  ASSIGNEE VARCHAR,
  DONE BOOLEAN,
);
  
CREATE TABLE REMINDERS (
  ISSUE_ID BIGINT,
  CREATED TIMESTAMP,
  TARGET TIMESTAMP,
); 